# Generated by Django 4.1 on 2024-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
