# Generated by Django 4.1 on 2024-04-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_pub_date_category_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_added',
        ),
    ]
