# Generated by Django 5.0.5 on 2024-05-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_slide_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeproduct', to='store.category'),
        ),
    ]
