# Generated by Django 4.1 on 2023-12-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
    ]
