# Generated by Django 4.1 on 2023-12-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wishlists'},
        ),
    ]
