# Generated by Django 4.1 on 2024-01-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_wished_product_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
