# Generated by Django 5.0.5 on 2024-05-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news',
            new_name='post',
        ),
    ]
