# Generated by Django 4.1 on 2024-04-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
    ]
