# Generated by Django 4.1 on 2023-12-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_shippingaddress_country_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
