# Generated by Django 4.1 on 2023-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(choices=[('ALGERIA', 'Algeria'), ('ANGOLA', 'Angola'), ('ARGENTINA', 'Angentina'), ('AUSTRALIA', 'Australia'), ('BELGIUM', 'Belgium'), ('BRAZIL', 'Brazil'), ('BURKINA FASO', 'Burkina Faso'), ('CANADA', 'Canada'), ('DENMARK', 'Denmark'), ('GHANA', 'Ghana')], default='GHANA', max_length=20),
        ),
    ]
