# Generated by Django 4.1 on 2023-12-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
