# Generated by Django 4.1 on 2024-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_orderitem_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivered',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not delivered', 'Not delivered')], default='Not delivered', max_length=50),
        ),
    ]
