# Generated by Django 4.1 on 2024-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_orderitem_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery',
            field=models.CharField(choices=[('INTERNATIONAL', 'International'), ('DOMESTIC', 'Domestic')], default='International', max_length=50),
        ),
    ]
