# Generated by Django 4.1 on 2024-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_shippingaddress_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='delivery',
            field=models.CharField(choices=[('INTERNATIONAL', 'International'), ('DOMESTIC', 'Domestic')], default='International', max_length=50),
        ),
    ]
