# Generated by Django 4.1 on 2024-04-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_shippingaddress_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='delivery',
        ),
    ]
